### ISSUE TITLE
Support es6 classes

### ISSUE THREAD

**Issue by tgandrews** [tgandrews/atom-easy-jsdoc#1]
When adding JSDoc next to class declarations and methods does just results in a generic block comment rather than picking up the metadata.

- [x] - Class definitions
- [x] - Class methods - By #2

**Comment by chikamichi** [comment]
That's cool you decided to work on this :)

**Comment by tgandrews** [comment]
All work done. I'll close this when I release 4.7.0

**Comment by tgandrews** [comment]
Closed with release 4.7.0
