### ISSUE TITLE
Uses @return instead of @returns

### ISSUE THREAD

**Issue by whitehat007** [tgandrews/atom-easy-jsdoc#10]
This came up when I ran my eslint check. Should be a pretty quick fix.

**Comment by tgandrews** [comment]
Which rule were you using? I've not seen this linting problem before

**Comment by tgandrews** [comment]
Also, thanks for the report :+1:

**Comment by whitehat007** [comment]
![image](https://cloud.githubusercontent.com/assets/11321893/13346957/0846781a-dc1f-11e5-84c2-a6756461d081.png)

**Comment by whitehat007** [comment]
Also I'm using eslint version 2.2.0.

**Comment by tgandrews** [comment]
This is an option and can be configured in the linting plugin. I will leave it as is for the moment but it have changed to match the default linting option in the beta version.
