### ISSUE TITLE
Option to limit comment continuation on /**

### ISSUE THREAD

**Issue by jitcoder** [tgandrews/atom-easy-jsdoc#14]
It would be great to be able to choose what kind of comments to do comment continuation on.

For example.

When I'm writting jsDoc comments I use /** (NOT //)

However I do use // to leave code comments (which are mostly short comments that don't need comment line continuation).

This plugin however does not let me limit to comment line continuation only to /**

**Comment by tgandrews** [comment]
I agree. It's not something I really use either. I will make continuing line comments an option and have it disabled by default.

I'm trying to make all new changes in the beta version. Would you be happy with me making the change there? This would mean that you would have to enable the beta version once it is released.

**Comment by jitcoder** [comment]
sure, I've monkey patched it for now

**Comment by PhiLhoSoft** [comment]
I have enabled the beta version, but I see no additional settings, even after reloading Atom.
Have you done this request? How I disable this continuation of single line comments?
It is tiring to delete `// ` systematically each time I want to add a line after a line comment! (and it is rather outside of the scope of JSDoc!).

**Comment by tgandrews** [comment]
Sorry, this issue is still open at the moment. I'll put this in tonight

**Comment by PhiLhoSoft** [comment]
Thanks.
Suggestion: maybe keep current behavior on Shift-Enter.
Ie. Enter just enter an un-prefixed line, and Shift-Enter prefixes the new line with `// `.
With proper options, etc. Can be useful in the rare cases when I really want to continue a line comment.
Shift+Enter has no key binding on my version of Atom...

Side note: I might have found a workaround, while investigating for these key bindings... I found out that Ctrl-Enter does a "newline-below", while Ctrl-Shift-Enter does a "newline-above".
I wondered of the difference between Ctrl-Enter and Enter. The former inserts a new line after the one where the caret was, whatever the position of the caret. Handy.
Interesting side effect: it doesn't trigger your auto-completion.

But, well, it will feel more natural to get that on regular Enter.

So, thanks again for fixing that. :smile:

**Comment by tgandrews** [comment]
I removed the comment continuation. I didn't see the shift-enter suggestion here - sorry. If you are still interested in this feature please open another issue for it. I personally wouldn't use it but if it gets some interest I'm happy to add it.

**Comment by PhiLhoSoft** [comment]
It is not compelling, and I might regularly forget to use it anyway...
But at least the suggestion is in the air, here to take by somebody. :smile:
