### ISSUE TITLE
function() with or without a space

### ISSUE THREAD

**Issue by jbree** [tgandrews/atom-easy-jsdoc#17]
When I insert a comment to a function declared like the following, it identifies that it is a method of `this`.

```
        /**
         * this - description        
         *          
         * @return {type}  description         
         */         
        this.functionWithoutSpace = function() {
            
        }
```

however, if I put a space between `function` and `()`, it calls it anonymous:
```

        /**
         * anonymous function - description        
         *          
         * @return {type}  description         
         */         
        this.functionWithSpace = function () {
            
        }
```

**Comment by tgandrews** [comment]
:+1: Thanks for the report.

This sounds completely possible. I will do some more investigation and ensure that the beta version supports this.
