### ISSUE TITLE
Extra '*' character in block comments.

### ISSUE THREAD

**Issue by brianmcallister** [tgandrews/atom-easy-jsdoc#23]
Hey there,

Just upgraded to v4.5.0, and I'm seeing extra `*` characters when pressing `enter` after `/** [tab]`. Here's a gif:

![untitled](https://cloud.githubusercontent.com/assets/708453/14724177/7f70f87c-07e2-11e6-89da-80b1634de84a.gif)

Let me know if there's any other information I can provide. Thanks!

**Comment by tgandrews** [comment]
:+1: Thanks for the report.

The package does not close multiline comments for you - what other packages do you have installed?

**Comment by brianmcallister** [comment]
Ah, good call, this was my mistake. Based on enabling/disabling some other packages of mine, it looks like this is a conflict with `language-babel`. However, it also looks like the last update in that package fixed this issue, so I'll just go ahead and close this.

**Comment by tgandrews** [comment]
Thanks, I'll keep an eye on that package to see if we get conflicts again.
