### ISSUE TITLE
Support ES async function

### ISSUE THREAD

**Issue by elado** [tgandrews/atom-easy-jsdoc#26]
```js
class X {
  async y() {
  }
}
```

Renders:

```js
class X {
  /**  
   * async - description  
   *    
   * @param  {type} z description   
   * @return {type}   description   
   */   
  async y(z) {
    
  }
}
```

`async` as a method name instead of `y`.

Needs to skip `async` if exists.

**Comment by tgandrews** [comment]
This should be a straightforward fix in the AST version aka beta. I won't
at this to the regex version.

**Comment by tgandrews** [comment]
This is an es 2016 feature - and currently I have only looked at es 2015 features. This will be delayed for a while unless lots of people say they are using.
