### ISSUE TITLE
Support Flow annotations

### ISSUE THREAD

**Issue by elado** [tgandrews/atom-easy-jsdoc#27]
``` js
class X {
  y(s: string, n: number) {
  }
}
```

Currently renders

``` js

class X {
  /**  
   * y - description  
   *    
   * @param  {type} s: string description   
   * @param  {type} n: number description   
   * @return {type}           description   
   */   
  y(s: string, n: number) {
  }
}
```

Types can be extracted after `:` if exist.

**Comment by tgandrews** [comment]
The only problem is that isn't valid JS so this will work with the legacy
regex version but not the AST version. Any ideas?

**Comment by tgandrews** [comment]
Looks like Babel supports it nicely so maybe this isn't so hard.

https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-flow

**Comment by tgandrews** [comment]
So, it is using a different parser. It would be interesting to find out why - but this parser supports flow.
https://github.com/babel/babylon
