### ISSUE TITLE
support es6 arrow functions

### ISSUE THREAD

**Issue by phipix01** [tgandrews/atom-easy-jsdoc#29]
```
let square = x => x*x
const drawRect = (posX, posY, sizeX, sizeY, canvas) => {
    ...
}
```

comment template generation for these cases would be great.
is someone already working on this? Otherwise I'd be keen on implementing it.

**Comment by tgandrews** [comment]
I'll take a look. Thanks for the use cases. I'll add tests to make sure
they are covered.
