### ISSUE TITLE
Support FunctionExpressions in ObjectExpressions

### ISSUE THREAD

**Issue by kostasmanionis** [tgandrews/atom-easy-jsdoc#33]
Is it me or something like this doesnt work? Getting an empty comment :(

```
const obj = {

    /**
     * 
     */
	foo(arg) {
    	return bar();
    }
}
```

**Comment by tgandrews** [comment]
I presume this is with the beta enabled? If so, I will look later this week. Thanks for the report :+1:

**Comment by kostasmanionis** [comment]
Yup, it's enabled.

**Comment by tgandrews** [comment]
Then they must be appearing as a different node type. I will have a look.
