### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by Trudko** [tgandrews/atom-easy-jsdoc#39]
Hi :),

first of all thank you for the package!

I would like to ask you if you are planning to include custom templates. I am using JSDoc for a library and each function have two extra lines which I need to include by hand every time.

Thank you for the answer.

**Comment by tgandrews** [comment]
What are these two extra lines?

**Comment by Trudko** [comment]
It's project specific , just imagine two strings. Normally I could use snippet for this because I have to edit part of those lines, but I would lost JSDoc parameter, gen. capabilities.

**Comment by tgandrews** [comment]
Are these two lines to include valid JSDoc parameters?

**Comment by Trudko** [comment]
No

**Comment by tgandrews** [comment]
Is it the same for each JSDoc comment?

**Comment by tgandrews** [comment]
Closing for the moment as I'm unlikely to need this. Please comment if you feel this is necessary.

**Comment by Trudko** [comment]
Sorry didn't notice your last comment. Yes it is same for all JSDoc comments.

**Comment by tgandrews** [comment]
I'll add this so you can add the additional lines in config.
