### ISSUE TITLE
Support ngdoc styling

### ISSUE THREAD

**Issue by jptinsman** [tgandrews/atom-easy-jsdoc#40]
could you support ng-doc style comments as well (use a checkbox to decide which to use)?

```
/**
 * @ngdoc function
 * @name [function name]
 * @description description
 *
 * ...
```

**Comment by tgandrews** [comment]
I found the [documentation](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation).

But as I do no angular development this is something I'm unlikely to support. I would be happy to accept a PR and it shouldn't be too big of a change as I already have a separate renderer for JSDoc - https://github.com/tgandrews/atom-easy-jsdoc/blob/master/lib/jsdoc/renderer.js

**Comment by tgandrews** [comment]
Closing as I'm not going to get round to this unless I start working with Angular
