### ISSUE TITLE
Recognize ES6 arrow syntax

### ISSUE THREAD

**Issue by ianwalter** [tgandrews/atom-easy-jsdoc#44]
For example, when adding jsdoc for the following:

```js
const hasIdentifier = el => el.hasAttribute('id') || el.hasAttribute('name')
```

Only a comment block is inserted:

```js
/**
 * 
 */ 
```

The plugin doesn't add the param or return lines like it does for functions written in the traditional syntax.

**Comment by tgandrews** [comment]
I think this was resolved with release `4.9.0` please can you confirm?

**Comment by tgandrews** [comment]
![reproduction failure](https://cloud.githubusercontent.com/assets/180903/22183302/a192c850-e0b2-11e6-8113-c82728f8421e.gif)

**Comment by ianwalter** [comment]
I didn't have beta enabled previously. After reinstalling and enabling beta this seems to be working correctly. I saw some strange behavior and got an error during the process but I can't reproduce them anymore. Thank you!
