### ISSUE TITLE
conflict with goto-definition in Atom 1.16.0 under macOS Sierra

### ISSUE THREAD

**Issue by ikzjfr0** [tgandrews/atom-easy-jsdoc#55]
when enabled, comes following error; when disabled, this error disappear

<img width="532" alt="eer" src="https://cloud.githubusercontent.com/assets/6456056/25741990/ad50c10a-31d0-11e7-8710-3c6ae2b7c2b2.png">

**Comment by tgandrews** [comment]
Interesting. Thanks for the report I'll investigate.

**Comment by tgandrews** [comment]
Can you please provide more details. Maybe a quick step by step guide or a quick screen capture?

**Comment by ikzjfr0** [comment]
![erro](https://cloud.githubusercontent.com/assets/6456056/25742746/3c6e4bca-31d4-11e7-94ac-9ad7ad1f1540.gif)
attached is an video. as long as it's disabled, it's working. When it's enabled, shortcut does not work any more

**Comment by ikzjfr0** [comment]
if you use the latest Atom beta version, you can see this info

<img width="1098" alt="dsfsd" src="https://cloud.githubusercontent.com/assets/6456056/25765132/b95ff20a-322e-11e7-8bd2-2d3eec57d11b.png">

**Comment by tgandrews** [comment]
Thanks a lot for the info. I'll have a look.

**Comment by tgandrews** [comment]
Closing as rebuilding the plugin on update - i.e. listening to the atom warnings resolves the issues.
