### ISSUE TITLE
Unavailable tag error should not be considered an error

### ISSUE THREAD

**Issue by jarrodek** [tgandrews/atom-easy-jsdoc#58]
I use Polymer and I'm building web components based on Polymer library. 

Polymer elements that display a documentation for the element uses tags in comments (for some reason). It also causes that jsDoc shows an error message, even if that's not an error.

It should be either an option to turn error reporting on or there should be a setting to add custom rules.

**Comment by tgandrews** [comment]
Thanks for the report. I'm not a polymer user would you be able to provide an example code snippet  and I'll happily look into it.

**Comment by tgandrews** [comment]
Reopening when more details are provided
