### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by jhabdas** [tgandrews/atom-easy-jsdoc#59]
I'm including a Doc Block I would like highlighted. Is that something this package attempts to achieve, or should I be looking for a different package for syntax highlighting?

<img width="250" alt="screen shot 2017-05-29 at 2 50 47 pm" src="https://cloud.githubusercontent.com/assets/440298/26539308/5d5933ce-447e-11e7-968c-728527374766.png">

**Comment by tgandrews** [comment]
I use just the core `language-javascript` package and get some basic highlighting
<img width="334" alt="screen shot 2017-06-09 at 12 13 23" src="https://user-images.githubusercontent.com/180903/26973204-28f072f4-4d0d-11e7-9545-e16090928517.png">
.

**Comment by jhabdas** [comment]
My bad I should've closed this. I was having the same issue with a different package and learned the syntax highlighting isn't done by the doc block tooling. In my case - because I'm lazy - I just updated to latest Atom and got highlighting with a bonus add of better speed (tough somehow it still feels the same).
