### ISSUE TITLE
Automatically insert jsdoc block when typing `/**`

### ISSUE THREAD

**Issue by NoNameProvided** [tgandrews/atom-easy-jsdoc#8]
It would be nice to automatically insert a jsdoc comment when the user enter `/**` It works like this in webstorm now and it makes the life a lot easier. Pressing Ctr + Shift + d is pretty hard to do every time. (You need to move your hand from the typing position if u want to press it.)

**Comment by tgandrews** [comment]
Sounds reasonable but needs investigation.

**Comment by julmot** [comment]
:+1:

**Comment by NoNameProvided** [comment]
The [docblockr](https://atom.io/packages/docblockr) extension support this feature, you can check it for  some hint on the how to.

**Comment by tgandrews** [comment]
Thanks. Will take a look

**Comment by julmot** [comment]
If docblockr handles all the stuff atom-easy-jsdoc does, why is it necessary at all?

**Comment by NoNameProvided** [comment]
> If docblockr handles all the stuff atom-easy-jsdoc does, why is it necessary at all?

Someone made Netscape back in time. Why did anyone else make an another browser?   
- it makes things go forward faster
- same thing can be implemented different ways, it gives you the freedom to choose what suits you best.
- performance differences

Eg. atom-easy-jsdoc loads under 5ms while dockblockr loads in 17 ms. In absolute measurement this is not a big difference because you cant really see the difference between 5ms and 17ms but relatively it loads 3x times faster. What is remarkable.

**Comment by julmot** [comment]
@NoNameProvided We are talking about such a small task that I don't think it will bring any benefits to rebuild it. Docblockr brings all the stuff that is missed in atom-easy-jsdoc (see this feature request requests to implement exactly the same functionality). 

So for me the situation is clear. Bye bye atom-easy.jsdoc :kiss:

**Comment by tgandrews** [comment]
That's a completely reasonable opinion. If you want to use another
extension that is fine by me.

I prefer the ux and use this extension as a learning tool, such as the
rewrite I am under taking to support es2015.

**Comment by NoNameProvided** [comment]
@julmot As I wrote I ended up using docblockr too. But your question was why did @tgandrews created the project. I replied to that question, it always make sense to have competitors.

**Comment by tgandrews** [comment]
As you guys seem to be no longer using the extension I'm closing this.
