### ISSUE TITLE
do you change paste manner? please 

### ISSUE THREAD

**Issue by we684123** [tgandrews/atom-easy-jsdoc#80]
do you change the way you paste jsdoc? please .

now use "atom-easy-jsdoc 4.12.5" to make a jsdoc wlii paste  line by line

like this ex:

```
function test(a,b){
  return a+b
}
```
use atom-easy-jsdoc (ctrl+shift+j) will make 

```
/**
 * test - description
 *  
 * @param  {type} a description 
 * @param  {type} b description 
 * @return {type}   description 
 */ 
function test(a,b){
  return a+b
}
```

but if i use "crtl+z"(undo)

atom will not undo all jsdoc , just will undo one line
like this :
```
/**
 * test - description
 *  
 * @param  {type} a description 
 * @param  {type} b description 
 * @return {type}   description 
 
function test(a,b){
  return a+b
}
```

i want to use ctrl+z will restore 
```
function test(a,b){
  return a+b
} 
```

//-----------------------------------
Thank you very much for making such a convenient kit.
This greatly helped us m(_ _)m

...and sorry to my bad english QwQ

**Comment by tgandrews** [comment]
I’ll have a look and see what I can do but the request is completely
reasonable

**Comment by we684123** [comment]
Github：「We are archiving Atom and all projects under the Atom organization for an official sunset on December 15, 2022.」
https://github.blog/2022-06-08-sunsetting-atom/
----
Thank you for developing the extension
