### ISSUE TITLE
Remove unnecessary blanks

### ISSUE THREAD

**Issue by julmot** [tgandrews/atom-easy-jsdoc#9]
Currently some unnecessary blanks will be generated:
![suppl](https://cloud.githubusercontent.com/assets/8310677/13251986/e8e1eb2c-da33-11e5-96ec-d3bfe8ae88ba.png)
- Two blanks after the description
- One blank after each @param or @return

**Comment by tgandrews** [comment]
Thanks for the report. I will look into this

**Comment by tgandrews** [comment]
This is resolved in the beta version.
